###############################################################################
#  Repository: mucoll-spack
#  Tag:        ${VERSION}-alma9
###############################################################################

ARG VERSION=release
FROM gitlab-registry.cern.ch/linuxsupport/alma9-base

# epel-release and parallel needed for the validation
# wget needed for some tests
RUN dnf update -y && \
    dnf groupinstall -y "Development Tools" && \
    dnf install -y vim gfortran wget python3-pip epel-release mesa-libGL mesa-libGL-devel mesa-libGLU mesa-libGLU-devel krb5-devel && \
    dnf install -y parallel ccache mold && \
    dnf clean all

RUN pip install boto3 requests

# Add the new Certificate Authority (needed for xrootd)
RUN wget https://uit.stanford.edu/sites/default/files/2023/10/11/incommon-rsa-ca2.pem -P /usr/share/pki/ca-trust-source/anchors && \
    /usr/bin/update-ca-trust

# Adding repositories: Spack
ARG SPACK_COMMIT=6cb16c39ab85fbc211e50be804fa7a15f24ccebc

# Setting up Spack
RUN git clone https://github.com/spack/spack.git /opt/spack && \
    echo "source /opt/spack/share/spack/setup-env.sh" >> /opt/setup_spack.sh && \
    echo "alias setup_spack=\"source /opt/setup_spack.sh\"" >> /etc/profile.d/aliases.sh

# Using specific commit of Key4hep repository if requested
RUN if [ -n "${SPACK_COMMIT}" ]; then \
      cd /opt/spack; \
      git checkout ${SPACK_COMMIT}; \
    fi

# Configure the spack environment with common settings.
# This includes:
# - Registering compilers with Spack.
# - Adding any buildcaches.
ENV SPACK_COLOR="always"
ARG SPACK_BUILDCACHE
RUN source /opt/setup_spack.sh && \
    spack compiler find && \
    if [ -n "${SPACK_BUILDCACHE}" ]; then \
        for buildcache in ${SPACK_BUILDCACHE//:/ }; do \
            spack mirror add --unsigned local-buildcache "${buildcache}"; \
        done \
    fi
