name: concretize-ubuntu

on: [pull_request]

jobs:
  concretize:
    strategy:
      fail-fast: false
      matrix:
        target: [common, release, release-debug]
    uses: ./.github/workflows/concretize-template.yaml
    with:
      target: ${{ matrix.target }}