name: Spack Build

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string

jobs:
  concretize:
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    steps:
      - name: Set up Spack
        uses: spack/setup-spack@v2
        with:
          ref: 6cb16c39ab85fbc211e50be804fa7a15f24ccebc # Spack version (examples: develop, releases/v0.23)
          buildcache: true                              # Configure oci://ghcr.io/spack/github-actions-buildcache
          color: true                                   # Force color output (SPACK_COLOR=always)
          path: spack                                   # Where to clone Spack
      - name: Checkout key4hep repository
        uses: actions/checkout@v4
        with:
          repository: key4hep/key4hep-spack
          path: spack/var/repo/key4hep-spack
      - name: Checkout mucoll repository
        uses: actions/checkout@v4
        with:
          path: spack/var/repo/mucoll-spack
      - name: Apply the patches
        shell: spack-bash {0}
        run: |
          spack/var/repo/mucoll-spack/AlmaLinux9/apply_patches.sh spack/var/repo/key4hep-spack/.cherry-pick
          spack/var/repo/mucoll-spack/AlmaLinux9/apply_patches.sh spack/var/repo/mucoll-spack/.cherry-pick
      - name: Spack Concretize
        shell: spack-bash {0}
        run: |
          spack --version
          spack repo add spack/var/repo/key4hep-spack
          spack repo add spack/var/repo/mucoll-spack
          spack compiler find
          spack env activate mucoll-spack/environments/mucoll-${{ inputs.target }}
          spack concretize
      - name: Spack Install
        shell: spack-bash {0}
        run: |
          spack install
      - name: Push Spack Packages
        env:
          GITHUB_USER: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: spack -e . buildcache push --base-image ubuntu:22.04 --update-index local-buildcache
        if: ${{ !cancelled() }}