name: Build and Publish Docker Image

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string

env:
  REGISTRY: ghcr.io

jobs:
  build-image:
    runs-on: ubuntu-24.04-arm
    strategy:
      matrix:
        os: [{dir: AlmaLinux9,suffix: alma9}]
    env:
      IMAGE_NAME: mucoll-${{inputs.image}}
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: endersonmenezes/free-disk-space@v2
        with:
          remove_android: true
          remove_dotnet: true
          remove_haskell: true
          remove_tool_cache: true
          remove_swap: true
          remove_packages: "azure-cli google-cloud-cli microsoft-edge-stable google-chrome-stable firefox postgresql* temurin-* *llvm* mysql* dotnet-sdk-*"
          remove_packages_one_command: true
          remove_folders: "/usr/share/swift /usr/share/miniconda /usr/share/az* /usr/share/glade* /usr/local/lib/node_modules /usr/local/share/chromium /usr/local/share/powershell"
          testing: false
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Make owner name lowercase
        run: |
            echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
            OWNER: '${{ github.repository_owner }}'
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{env.OWNER_LC}}/mucoll-dummy
      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: ./${{matrix.os.dir}}
          file: ./${{matrix.os.dir}}/Dockerfile-${{inputs.image}}
          push: true
          build-args: |
            VERSION=${{ steps.meta.outputs.version }}
            REPOSITORY=${{ env.REGISTRY }}/${{env.OWNER_LC}}
            GITHUB_REPOSITORY=${{ github.repository }}
            MUCOLL_SHA=${{ github.sha }}
            SPACK_BUILDCACHE=oci://ghcr.io/${{ github.repository_owner }}/spack-buildcache
          tags: ${{ env.REGISTRY }}/${{env.OWNER_LC}}/${{ env.IMAGE_NAME}}:${{steps.meta.outputs.version}}-${{matrix.os.suffix}}
          labels: ${{ steps.meta.outputs.labels }}
