name: Re-build and publish MuColl

on:
  push:
    paths:
        - '.github/workflows/mucoll-rebuild.yml'
        - '.cherry-pick'
        - 'AlmaLinux9/Dockerfile-sim'
        - 'environments/**'
        - 'packages/**'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

permissions:
  contents: read
  packages: write
  id-token: write
  attestations: write

jobs:
  build-sim:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [{dir: AlmaLinux9,suffix: alma9}]
    env:
      IMAGE_NAME: mucoll-sim
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: endersonmenezes/free-disk-space@v2
        with:
          remove_android: true
          remove_dotnet: true
          remove_haskell: true
          remove_tool_cache: true
          remove_swap: true
          remove_packages: "azure-cli google-cloud-cli microsoft-edge-stable google-chrome-stable firefox postgresql* temurin-* *llvm* mysql* dotnet-sdk-*"
          remove_packages_one_command: true
          remove_folders: "/usr/share/swift /usr/share/miniconda /usr/share/az* /usr/share/glade* /usr/local/lib/node_modules /usr/local/share/chromium /usr/local/share/powershell"
          testing: false
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/mucoll-dummy
      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./${{matrix.os.dir}}
          file: ./${{matrix.os.dir}}/Dockerfile-sim
          build-args: |
            VERSION=${{ steps.meta.outputs.version }}
            REPOSITORY=${{ env.REGISTRY }}/${{ github.repository_owner }}
            GITHUB_REPOSITORY=${{ github.repository }}
            MUCOLL_SHA=${{ github.sha }}
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME}}:${{steps.meta.outputs.version}}-${{matrix.os.suffix}}
